Repository fga-eps-mds/2019.2-Chatbot-Nilo, pull requests merged in 2019-11, with the labels that each got.

#82 Fix #74 Criando novas respostas para dúvidas referentes a Coordenação e Secretaria.
  coach/data/intents/estagio.md
  coach/data/intents/geral.md
  coach/data/stories/estagio.md
  coach/data/stories/geral.md
  coach/domain.yml
Labels: 0 - P.O, 1 - Requisitos, 2 - UX, enhancement

#84 Fix #59 resolve testes falhos do test style no CI
  bot/actions/actions.py
  bot/actions/webscraping.py
Labels: 0 - Developers, Fix

#83 Fix #70 adicionando /help
  coach/data/intents/examples.md
  coach/data/intents/geral.md
  coach/data/stories/examples.md
  coach/data/stories/geral.md
  coach/domain.yml
Labels: 0 - Developers, 1 - Requisitos, 2 - UX, 3 - Débito Técnico, 4 - Iniciante

#87 Fix #86 Correção de erro no arquivo de WebScraping
  bot/actions/webscraping.py
Labels: 0 - Developers, 1 - Viabilidade Técnica, 4 - Iniciante, Fix

#90 #85 Consertando o CI e os testes do bot
  .gitlab-ci.yml
  Makefile
  bot/e2e/e2e_stories.md
  docker/bot.Dockerfile
  docker/build-base.sh
Labels: 0 - DevOps, 0 - Developers, 2 - Integraçã Contínua, 2 - Test, 3 - Débito Técnico, Fix

#91 #89 Editando o /start com os novos assuntos adicionados ao bot.
  coach/domain.yml
Labels: 0 - Developers, 1 - Requisitos, 2 - UX, 4 - Iniciante, Fix

#93 Fix #92 Altera o nome das imagens do bot para evitar conflitos.
  docker/actions.Dockerfile
  docker/coach.Dockerfile
  docker/notebooks.Dockerfile
Labels: 0 - Developers, 1 - Viabilidade Técnica, 2 - Test, 4 - Iniciante, Bug, Fix

#94 Fix #93 Alterando o nome da tag do build para "yukioz/requirements."
  docker-compose.yml
Labels: 0 - Developers, 1 - Viabilidade Técnica, 2 - Test, 4 - Iniciante, Bug, Fix, HOTFIX

#96 Fix #88 Adição da configuração e do tutorial de deploy no repositório
  deploy/nginx.conf
  deploy/sites-available/nilofga.gq
  deploy/sites-enabled/nilofga.gq
  deploy/tutorial.md
Labels: 0 - DevOps, 1 - Viabilidade Técnica, 4 - Avançado

#98 Fix #97 Adicionando a opção que responde quais são os tópicos conhecidos pelo bot Nilo
  coach/data/intents/examples.md
  coach/data/stories/examples.md
  coach/domain.yml
Labels: 0 - Developers, 2 - UX, 4 - Intermediario, enhancement

#99 Fix #95 Consertando a action para enviar o doc de faq_estagio
  bot/actions/actions.py
Labels: 0 - Developers, 1 - Requisitos, 4 - Intermediario, Fix

#101 Fix #100 Atualiza o README.
  README.md
  assets/Nilo_logo.jpg
  assets/iN8Xdx5.gif
  assets/matricula.jpg
  assets/send_doc.jpg
  assets/start.jpg
  docs/img/Nilo_logo_pequeno.png
  docs/img/prototipo_atividades_estagio.jpeg
  docs/img/prototipo_despedida.jpeg
Labels: 1 - Documentação, 2 - Comunidade, HOTFIX

#104 Fix #102 Adiciona documentos de metodologia.
  README.md
  assets/ciclo_scrum.gif
  assets/gif_start.gif
  assets/roles.png
  docs/metedologia.md
  docs/métricas/Burndown_Report/burndown_sprint10.png
  docs/métricas/Burndown_Report/burndown_sprint11.png
  docs/métricas/Burndown_Report/burndown_sprint12.png
  docs/métricas/Burndown_Report/burndown_sprint13.png
  docs/métricas/Burndown_Report/burndown_sprint4.png
  docs/métricas/Burndown_Report/burndown_sprint5.png
  docs/métricas/Burndown_Report/burndown_sprint6.png
  docs/métricas/Burndown_Report/burndown_sprint7.png
  docs/métricas/Burndown_Report/burndown_sprint8.png
  docs/métricas/Burndown_Report/burndown_sprint9.png
  sprints/sprint10.md
  sprints/sprint11.md
  sprints/sprint9.md
  sprints/sprint_8.md
Labels: 1 - Documentação, 2 - Comunidade, HOTFIX

#105 Fix/readme
  README.md
  docs/Escopo.md
Labels: 0 - Scrum Master, 1 - Documentação

#106 #103 "Testes Finais"
  bot/e2e/e2e_stories.md
  coach/data/intents/examples.md
  coach/data/stories/actions.md
Labels: 0 - Developers, 1 - Viabilidade Técnica, 2 - Test

#108 Fix #107 Criando exceções para as actions.
  bot/actions/actions.py
Labels: 0 - Developers, 1 - Viabilidade Técnica, 2 - UX, HOTFIX
