Repository fga-eps-mds/2019.2-Chatbot-Nilo, pull requests merged in 2019-10, with the labels that each got.

#33 Feature/fix estagio
  bot/actions/FAQ_Estagio.txt
  bot/actions/FAQ_Geral.txt
  bot/actions/actions.py
  bot/actions/procura_respostas.py
  coach/data/intents/actions.md
  coach/data/intents/estagio.md
  coach/data/stories/actions.md
  coach/data/stories/estagio.md
  coach/domain.yml
Labels: 0 - Developers, 1 - Viabilidade Técnica, Fix

#36 Fix/Políticas de branches e de Pull Request.
  .github/política_branches_commits/Git-flow.md
  .github/pull_request_template.md
Labels: 0 - Scrum Master, 1 - Documentação, 2 - Comunidade, Fix

#37 Fix templates de Pull Request e nome das branches de correção.
  .github/política_branches_commits/Git-flow.md
  .github/pull_request_template.md
Labels: 0 - Scrum Master, 1 - Documentação, 2 - Comunidade, Fix

#39 #35 Adicionado código de conduta
  .github/CODE_OF_CONDUCT.md
Labels: 0 - Scrum Master, 1 - Documentação, 2 - Comunidade

#40 Fix #38 Corrige novamente o template de Pull Request.
  .github/pull_request_template.md
Labels: 0 - Scrum Master, 1 - Documentação, 2 - Comunidade, Fix

#42 Fix #34 Adiciona o Guia de contribuição do repositório.
  .github/CONTRIBUTING.md
Labels: 1 - Documentação, 2 - Comunidade

#48 Fix #46 Links quebrados
  .github/CONTRIBUTING.md
Labels: 1 - Documentação, Fix

#50 Fix #30 Reformula o escopo do projeto e atualiza o documento.
  docs/Escopo.md
Labels: 0 - P.O, 1 - Documentação, 3 - Débito Técnico, Fix, Review

#54 Fix #27 Corrigir documento de arquitetura
  docs/DocumentoDeArquitetura.md
Labels: 1 - Arquitetura, 1 - Documentação, 3 - Débito Técnico, Fix

#55 Fix #53 Redefine o Roadmap.
  docs/Roadmap.md
Labels: 0 - Scrum Master, 1 - Documentação, 2 - Roadmap, 3 - Débito Técnico, Fix, Review

#57 Fix #56 Testes refeitos
  bot/e2e/e2e_stories.md
Labels: 0 - Developers, 1 - Viabilidade Técnica, 2 - Test

#58 Fix #49 Nova action para reunir as informações dos coordenadores de estágio
  bot/actions/actions.py
  bot/actions/webscraping.py
  coach/data/intents/actions.md
  coach/data/intents/estagio.md
  coach/data/stories/actions.md
  coach/data/stories/estagio.md
  coach/domain.yml
  coach/policy_config.yml
  requirements.txt
Labels: 0 - Developers, 1 - Viabilidade Técnica, 4 - Intermediario, enhancement

#64 Fix #63 "Completando a action de coordenadores".
  bot/actions/actions.py
Labels: 0 - Developers

#62 Fix #28 Corrige o README.
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/img/Nilo_logo_pequeno.jpg
  docs/img/Nilo_logo_pequeno.png
  docs/img/iN8Xdx5.gif
  docs/img/prototipo_atividades_estagio.jpeg
  docs/img/prototipo_despedida.jpeg
Labels: 0 - Developers, 1 - Documentação, 1 - Viabilidade Técnica, 2 - Comunidade

#68 Fix #66 Usando nomes mais significativos
  bot/actions/webscraping.py
Labels: 0 - Developers, 2 - Comunidade, 4 - Intermediario, Review

#69 #61 Adicionando documentos de estágio que o bot envia
  bot/actions/actions.py
  coach/data/intents/actions.md
  coach/data/intents/estagio.md
  coach/data/stories/actions.md
  coach/data/stories/estagio.md
  coach/domain.yml
Labels: 0 - Developers, 1 - Requisitos, 2 - UX, enhancement
